from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class News(models.Model):
    penulis = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    judul = models.CharField(max_length=200) 
    konten = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    picture = models.URLField(blank=True, null=True)
    
    def __str__(self):
        return "{} - {}".format(self.judul, self.konten)
    

class Masakan(models.Model):
    idMeal = models.CharField(max_length=200, blank=True, null=True)
    strArea = models.CharField(max_length=200, blank=True, null=True) 
    strCategory = models.CharField(max_length=200, blank=True, null=True)
    strMeal = models.CharField(max_length=200, blank=True, null=True)
    strMealThumb = models.CharField(max_length=200, blank=True, null=True)
    strInstructions = models.TextField()
    strYoutube = models.CharField(max_length=225, blank=True, null=True)
    strIngredient1 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient2 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient3 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient4 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient5 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient6 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient7 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient8 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient9 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient10 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient11 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient12 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient13 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient14 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient15 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient16 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient17 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient18 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient19 = models.CharField(max_length=225, blank=True, null=True)
    strIngredient20 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure1 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure2 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure3 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure4 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure5 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure6 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure7 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure8 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure9 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure10 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure11 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure12 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure13 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure14 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure15 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure16 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure17 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure18 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure19 = models.CharField(max_length=225, blank=True, null=True)
    strMeasure20 = models.CharField(max_length=225, blank=True, null=True)
    
    def __str__(self):
        return "{} - {}".format(self.strMeal, self.strCategory)
    